<a href="https://colab.research.google.com/github/Ebratul/Python/blob/main/ML/IMDB_Data_Fetch_API_call.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests

In [10]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=effa57ee63ee347383ea69b5dfbb61c3&language=en-US&page=1').json()

In [20]:
# response

In [14]:
response['total_pages']

53901

In [16]:
response['total_results']

1078005

In [31]:
# response['results']

In [54]:
for i in response['results']:
  print(i['title'],i['release_date'])

Bureau 749 2024-10-01
The Shadow's Edge 2025-08-16
The Family Plan 2 2025-11-11
Altered 2025-09-18
Zootopia 2 2025-11-26
Frankenstein 2025-10-17
Wicked: For Good 2025-11-19
One Battle After Another 2025-09-23
A Legend 2024-07-05
The Gentleman 2025-09-26
Art of Eight Limbs 2024-08-16
Predator: Badlands 2025-11-05
JUJUTSU KAISEN: Execution -Shibuya Incident x The Culling Game Begins- 2025-11-07
War of the Worlds 2025-07-29
High Ground 2025-03-17
She Rides Shotgun 2025-07-31
Nahual 2025-02-06
Now You See Me: Now You Don't 2025-11-12
Playdate 2025-11-05
Demon Slayer: Kimetsu no Yaiba Infinity Castle 2025-07-18

In [28]:
import pandas as pd

In [30]:
d = {
    'name':['rahim', 'karim'],
    'Age':[22, 25]
}
df = pd.DataFrame(d)
df

    name  Age
0  rahim   22
1  karim   25

In [55]:
adult = []
genre_ids = []
id = []
original_language = []
original_title = []
overview = []
popularity = []
release_date = []
video = []
vote_average = []
vote_count = []
title = []

In [64]:
for i in response['results']:
  id.append(i['id'])
  adult.append(i['adult'])
  overview.append(i['overview'])
  title.append(i['title'])
  release_date.append(i['release_date'])
  vote_average.append(i['vote_average'])
  popularity.append(i['popularity'])
  vote_count.append(i['vote_count'])
  video.append(i['video'])
  original_language.append(i['original_language'])
  original_title.append(i['original_title'])

d = {
      'id':id,
      'adult':adult,
      'overview':overview,
      'title':title,
      'release_date':release_date,
      'vote_average':vote_average,
      'popularity':popularity,
      'vote_count':vote_count,
      'video':video,
      'original_language':original_language,
      'original_title':original_title
  }

df = pd.DataFrame(d)

In [57]:
d['title'][0]

'Bureau 749'

In [59]:
len(d['original_title'])

20

In [65]:
df.head(5)

,id,adult,overview,title,release_date,vote_average,popularity,vote_count,video,original_language,original_title
0,1033462,False,A traumatized young man with physical abnormal...,Bureau 749,2024-10-01,5.600,470.2154,35,False,zh,749局
1,1419406,False,Macau Police brings the tracking expert police...,The Shadow's Edge,2025-08-16,6.335,449.5069,115,False,zh,捕风追影
2,1363123,False,"Now that Dan's assassin days are behind him, a...",The Family Plan 2,2025-11-11,6.787,405.8007,188,False,en,The Family Plan 2
3,1309012,False,"In an alternate present, genetically enhanced ...",Altered,2025-09-18,6.471,326.3552,34,False,en,Altered
4,1084242,False,After cracking the biggest case in Zootopia's ...,Zootopia 2,2025-11-26,7.600,322.0511,64,False,en,Zootopia 2

In [62]:
df['adult'].value_counts()

adult
False    20
Name: count, dtype: int64

In [88]:
#another way
columns = [
    'id', 'adult', 'overview', 'title', 'release_date',
    'vote_average', 'popularity', 'vote_count', 'video',
    'original_language', 'original_title'
]
data_2d = []
for item in response['results']:
    row = []
    for col in columns:
        row.append(item.get(col))
    data_2d.append(row)

df = pd.DataFrame(data_2d, columns=columns)
df
# data_2d = []
# for item in response['results']:
#     data_2d.append([item[col] for col in columns])

,id,adult,overview,title,release_date,vote_average,popularity,vote_count,video,original_language,original_title
0,1033462,False,A traumatized young man with physical abnormal...,Bureau 749,2024-10-01,5.600,470.2154,35,False,zh,749局
1,1419406,False,Macau Police brings the tracking expert police...,The Shadow's Edge,2025-08-16,6.335,449.5069,115,False,zh,捕风追影
2,1363123,False,"Now that Dan's assassin days are behind him, a...",The Family Plan 2,2025-11-11,6.787,405.8007,188,False,en,The Family Plan 2
3,1309012,False,"In an alternate present, genetically enhanced ...",Altered,2025-09-18,6.471,326.3552,34,False,en,Altered
4,1084242,False,After cracking the biggest case in Zootopia's ...,Zootopia 2,2025-11-26,7.600,322.0511,64,False,en,Zootopia 2
5,1062722,False,"Dr. Victor Frankenstein, a brilliant but egoti...",Frankenstein,2025-10-17,7.773,248.0390,1896,False,en,Frankenstein
6,967941,False,As an angry mob rises against the Wicked Witch...,Wicked: For Good,2025-11-19,6.763,225.8664,268,False,en,Wicked: For Good
7,1054867,False,Washed-up revolutionary Bob exists in a state ...,One Battle After Another,2025-09-23,7.494,180.0008,1664,False,en,One Battle After Another
8,1116465,False,An archeologist noticed that the texture of th...,A Legend,2024-07-05,6.769,179.7004,104,False,zh,传说
9,1426968,False,Aging ex-soldier Theo meets weekly with prosti...,The Gentleman,2025-09-26,6.100,170.7684,11,False,es,Ya no quedan junglas
10,1208561,False,Four canisters of deadly VX nerve gas have fal...,Art of Eight Limbs,2024-08-16,6.019,169.0676,27,False,en,Art of Eight Limbs
11,1242898,False,"Cast out from his clan, a young Predator finds...",Predator: Badlands,2025-11-05,7.434,168.9922,459,False,en,Predator: Badlands
12,1539104,False,A veil abruptly descends over the busy Shibuya...,JUJUTSU KAISEN: Execution -Shibuya Incident x ...,2025-11-07,4.229,168.7133,35,False,ja,劇場版 呪術廻戦「渋谷事変 特別編集版」×「死滅回游 先行上映」
13,755898,False,Will Radford is a top analyst for Homeland Sec...,War of the Worlds,2025-07-29,4.303,166.6870,755,False,en,War of the Worlds
14,1433719,False,"When a mysterious prisoner lands in jail, a bo...",High Ground,2025-03-17,5.790,164.0787,31,False,en,High Ground
15,1196573,False,Newly released from prison and marked for deat...,She Rides Shotgun,2025-07-31,7.000,131.8899,66,False,en,She Rides Shotgun
16,1481331,False,Katia Montero's exotic getaway spirals into te...,Nahual,2025-02-06,3.200,130.2622,8,False,en,Nahual
17,425274,False,The original Four Horsemen reunite with a new ...,Now You See Me: Now You Don't,2025-11-12,6.276,129.3633,263,False,en,Now You See Me: Now You Don't
18,1248226,False,When out-of-work accountant Brian joins stay-a...,Playdate,2025-11-05,6.100,127.8036,307,False,en,Playdate
19,1311031,False,The Demon Slayer Corps are drawn into the Infi...,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,7.592,127.2527,578,False,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来

In [92]:
tmdb_movie_genres = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}
columns = [
    'id', 'adult', 'overview', 'genres', 'title', 'release_date',
    'vote_average', 'popularity', 'vote_count', 'video',
    'original_language', 'original_title'
]

data_2d = []
for item in response['results']:
    genre_ids = item.get('genre_ids', [])
    genre_names = [tmdb_movie_genres.get(gid, 'Unknown') for gid in genre_ids]
    genre_string = ', '.join(genre_names)
    row = []
    for col in columns:
        if col == 'genres':
            row.append(genre_string)
        else:
            row.append(item.get(col))
    data_2d.append(row)
df = pd.DataFrame(data_2d, columns=columns)
df['genres'].isnull().sum()
df.head(5)

,id,adult,overview,genres,title,release_date,vote_average,popularity,vote_count,video,original_language,original_title
0,1033462,False,A traumatized young man with physical abnormal...,"Action, Adventure, Science Fiction",Bureau 749,2024-10-01,5.600,470.2154,35,False,zh,749局
1,1419406,False,Macau Police brings the tracking expert police...,"Action, Crime, Thriller",The Shadow's Edge,2025-08-16,6.335,449.5069,115,False,zh,捕风追影
2,1363123,False,"Now that Dan's assassin days are behind him, a...","Action, Comedy",The Family Plan 2,2025-11-11,6.787,405.8007,188,False,en,The Family Plan 2
3,1309012,False,"In an alternate present, genetically enhanced ...","Science Fiction, Action",Altered,2025-09-18,6.471,326.3552,34,False,en,Altered
4,1084242,False,After cracking the biggest case in Zootopia's ...,"Animation, Family, Comedy, Adventure, Mystery",Zootopia 2,2025-11-26,7.600,322.0511,64,False,en,Zootopia 2

In [81]:
df['genres'].isnull().sum()

np.int64(0)

In [96]:
tmdb_movie_genres = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}
columns = [
    'id', 'adult', 'overview', 'genres', 'title', 'release_date',
    'vote_average', 'popularity', 'vote_count', 'video',
    'original_language', 'original_title'
]

data_2d = []

for j in range(1, 501):
  response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=effa57ee63ee347383ea69b5dfbb61c3&language=en-US&page={}'.format(j)).json()
  for item in response['results']:
    genre_ids = item.get('genre_ids', [])
    genre_names = [tmdb_movie_genres.get(gid, 'Unknown') for gid in genre_ids]
    genre_string = ', '.join(genre_names)
    row = []
    for col in columns:
      if col == 'genres':
        row.append(genre_string)
      else:
        row.append(item.get(col))
      data_2d.append(row)
df = pd.DataFrame(data_2d, columns=columns)

(120000, 12)

In [97]:
df.shape

(120000, 12)

In [99]:
df.isnull().sum()

id                   0
adult                0
overview             0
genres               0
title                0
release_date         0
vote_average         0
popularity           0
vote_count           0
video                0
original_language    0
original_title       0
dtype: int64

In [100]:
df.to_csv('my_IMDB_movies.csv')